name: Build and Test

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./TestResults

    - name: Install ReportGenerator
      if: matrix.os == 'ubuntu-latest'
      run: dotnet tool install --global dotnet-reportgenerator-globaltool

    - name: Generate coverage report
      if: matrix.os == 'ubuntu-latest'
      run: |
        reportgenerator \
          -reports:"TestResults/**/coverage.cobertura.xml" \
          -targetdir:"coveragereport" \
          -reporttypes:"Html;Cobertura;MarkdownSummaryGithub;TextSummary"

    - name: Display coverage summary
      if: matrix.os == 'ubuntu-latest'
      run: cat coveragereport/Summary.txt

    - name: Add coverage summary to job summary
      if: matrix.os == 'ubuntu-latest'
      run: |
        echo "## 📊 Code Coverage Report" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        cat coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage report artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coveragereport/
        retention-days: 7

    - name: Upload coverage reports to Codecov
      if: matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: 'coveragereport/Cobertura.xml'
        fail_ci_if_error: false

  build-native:
    name: Native AOT Build - ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    needs: test
    strategy:
      matrix:
        config:
          - name: "Windows x64"
            os: windows-latest
            rid: win-x64
            output: redmine.exe
          - name: "macOS x64"
            os: macos-latest
            rid: osx-x64
            output: redmine
          - name: "macOS ARM64"
            os: macos-latest
            rid: osx-arm64
            output: redmine
          - name: "Linux x64"
            os: ubuntu-latest
            rid: linux-x64
            output: redmine
          - name: "Linux ARM64"
            os: ubuntu-24.04-arm
            rid: linux-arm64
            output: redmine

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}


    - name: Restore dependencies
      run: dotnet restore

    - name: Publish Native AOT
      run: |
        dotnet publish RedmineCLI/RedmineCLI.csproj -c Release -r ${{ matrix.config.rid }} -p:PublishAot=true -p:StripSymbols=true --self-contained -o publish/${{ matrix.config.rid }}

    - name: Check binary size (Unix)
      if: runner.os != 'Windows'
      run: |
        if [[ "$RUNNER_OS" == "macOS" ]]; then
          BINARY_SIZE=$(stat -f%z "publish/${{ matrix.config.rid }}/${{ matrix.config.output }}")
        else
          BINARY_SIZE=$(stat -c%s "publish/${{ matrix.config.rid }}/${{ matrix.config.output }}")
        fi
        BINARY_SIZE_MB=$((BINARY_SIZE / 1024 / 1024))
        echo "Binary size: ${BINARY_SIZE_MB}MB"
        if [ $BINARY_SIZE_MB -gt 20 ]; then
          echo "Warning: Binary size exceeds 20MB target"
        fi

    - name: Check binary size (Windows)
      if: runner.os == 'Windows'
      run: |
        $BinarySize = (Get-Item "publish/${{ matrix.config.rid }}/${{ matrix.config.output }}").Length
        $BinarySizeMB = [math]::Round($BinarySize / 1024 / 1024, 2)
        Write-Output "Binary size: ${BinarySizeMB}MB"
        if ($BinarySizeMB -gt 20) {
          Write-Output "Warning: Binary size exceeds 20MB target"
        }

    - name: Test binary execution
      # Skip execution test for cross-compiled architectures
      if: |
        !(matrix.config.os == 'ubuntu-latest' && matrix.config.rid == 'linux-arm64') &&
        !(matrix.config.os == 'macos-latest' && matrix.config.rid == 'osx-arm64' && runner.arch != 'ARM64')
      run: publish/${{ matrix.config.rid }}/${{ matrix.config.output }} --version

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: redmine-cli-${{ matrix.config.rid }}
        path: publish/${{ matrix.config.rid }}/${{ matrix.config.output }}
        retention-days: 30

  benchmark:
    name: Performance Benchmark
    runs-on: ubuntu-latest
    needs: build-native
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Linux binary
      uses: actions/download-artifact@v4
      with:
        name: redmine-cli-linux-x64
        path: ./bin

    - name: Make binary executable
      run: chmod +x ./bin/redmine

    - name: Benchmark startup time
      run: |
        echo "Measuring startup time..."
        > startup_times.txt
        for i in {1..10}; do
          START=$(date +%s.%N)
          ./bin/redmine --version > /dev/null 2>&1
          END=$(date +%s.%N)
          DURATION=$(echo "$END - $START" | bc)
          echo "$DURATION" >> startup_times.txt
          echo "Run $i: ${DURATION}s"
        done
        
        # Calculate average
        AVG=$(awk '{sum+=$1; count++} END {print sum/count}' startup_times.txt)
        echo "Average startup time: ${AVG}s"

    - name: Check binary startup time
      run: |
        # Quick startup time check (should be under 1 second for CI)
        timeout 2s time ./bin/redmine --version
        echo "Startup time check passed"